name: Validate PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v2.2.0
        with:
          preset: conventional-changelog-conventionalcommits@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
